CREATE TABLE `ad_accounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accountId` varchar(64) NOT NULL,
	`accountName` varchar(255) NOT NULL,
	`marketplace` varchar(32) NOT NULL,
	`profileId` varchar(64),
	`conversionValueType` enum('sales','units','custom') DEFAULT 'sales',
	`conversionValueSource` enum('platform','custom') DEFAULT 'platform',
	`intradayBiddingEnabled` boolean DEFAULT true,
	`defaultMaxBid` decimal(10,2) DEFAULT '2.00',
	`status` enum('active','paused','archived') DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ad_accounts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ad_groups` (
	`id` int AUTO_INCREMENT NOT NULL,
	`campaignId` int NOT NULL,
	`adGroupId` varchar(64) NOT NULL,
	`adGroupName` varchar(500) NOT NULL,
	`defaultBid` decimal(10,2),
	`impressions` int DEFAULT 0,
	`clicks` int DEFAULT 0,
	`spend` decimal(10,2) DEFAULT '0.00',
	`sales` decimal(10,2) DEFAULT '0.00',
	`orders` int DEFAULT 0,
	`adGroupStatus` enum('enabled','paused','archived') DEFAULT 'enabled',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ad_groups_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `bidding_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`campaignId` int NOT NULL,
	`adGroupId` int,
	`logTargetType` enum('keyword','product_target','placement') NOT NULL,
	`targetId` int NOT NULL,
	`targetName` varchar(500),
	`logMatchType` varchar(32),
	`actionType` enum('increase','decrease','set') NOT NULL,
	`previousBid` decimal(10,2) NOT NULL,
	`newBid` decimal(10,2) NOT NULL,
	`bidChangePercent` decimal(5,2),
	`reason` text,
	`algorithmVersion` varchar(32),
	`performanceData` json,
	`isIntradayAdjustment` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `bidding_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `campaigns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`performanceGroupId` int,
	`campaignId` varchar(64) NOT NULL,
	`campaignName` varchar(500) NOT NULL,
	`campaignType` enum('sp_auto','sp_manual','sb','sd') NOT NULL,
	`targetingType` enum('auto','manual') DEFAULT 'manual',
	`maxBid` decimal(10,2),
	`intradayBiddingEnabled` boolean,
	`campaignConversionValueType` enum('sales','units','custom','inherit') DEFAULT 'inherit',
	`campaignConversionValueSource` enum('platform','custom','inherit') DEFAULT 'inherit',
	`placementTopSearchBidAdjustment` int DEFAULT 0,
	`placementProductPageBidAdjustment` int DEFAULT 0,
	`placementRestBidAdjustment` int DEFAULT 0,
	`impressions` int DEFAULT 0,
	`clicks` int DEFAULT 0,
	`spend` decimal(10,2) DEFAULT '0.00',
	`sales` decimal(10,2) DEFAULT '0.00',
	`orders` int DEFAULT 0,
	`acos` decimal(5,2),
	`roas` decimal(10,2),
	`ctr` decimal(5,4),
	`cvr` decimal(5,4),
	`cpc` decimal(10,2),
	`campaignStatus` enum('enabled','paused','archived') DEFAULT 'enabled',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `campaigns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `daily_performance` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`campaignId` int,
	`performanceGroupId` int,
	`date` timestamp NOT NULL,
	`impressions` int DEFAULT 0,
	`clicks` int DEFAULT 0,
	`spend` decimal(10,2) DEFAULT '0.00',
	`sales` decimal(10,2) DEFAULT '0.00',
	`orders` int DEFAULT 0,
	`dailyAcos` decimal(5,2),
	`dailyRoas` decimal(10,2),
	`conversions` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `daily_performance_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `import_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accountId` int,
	`fileName` varchar(255) NOT NULL,
	`fileUrl` varchar(1000),
	`fileType` enum('csv','excel') NOT NULL,
	`reportType` varchar(64),
	`importStatus` enum('pending','processing','completed','failed') DEFAULT 'pending',
	`totalRows` int,
	`processedRows` int DEFAULT 0,
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `import_jobs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `keywords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`adGroupId` int NOT NULL,
	`keywordId` varchar(64),
	`keywordText` varchar(500) NOT NULL,
	`matchType` enum('broad','phrase','exact') NOT NULL,
	`bid` decimal(10,2) NOT NULL,
	`suggestedBid` decimal(10,2),
	`impressions` int DEFAULT 0,
	`clicks` int DEFAULT 0,
	`spend` decimal(10,2) DEFAULT '0.00',
	`sales` decimal(10,2) DEFAULT '0.00',
	`orders` int DEFAULT 0,
	`keywordAcos` decimal(5,2),
	`keywordCtr` decimal(5,4),
	`keywordCvr` decimal(5,4),
	`estimatedTraffic` int,
	`trafficCeiling` int,
	`optimalBid` decimal(10,2),
	`marginalRevenue` decimal(10,2),
	`marginalCost` decimal(10,2),
	`keywordStatus` enum('enabled','paused','archived') DEFAULT 'enabled',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `keywords_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `market_curve_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`curveTargetType` enum('keyword','product_target') NOT NULL,
	`curveTargetId` int NOT NULL,
	`bidLevel` decimal(10,2) NOT NULL,
	`estimatedImpressions` int,
	`estimatedClicks` int,
	`estimatedConversions` decimal(10,2),
	`estimatedSpend` decimal(10,2),
	`estimatedSales` decimal(10,2),
	`curveMarginalRevenue` decimal(10,2),
	`curveMarginalCost` decimal(10,2),
	`marginalProfit` decimal(10,2),
	`curveTrafficCeiling` int,
	`optimalBidPoint` decimal(10,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `market_curve_data_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `performance_groups` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accountId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`optimizationGoal` enum('maximize_sales','target_acos','target_roas','daily_spend_limit','daily_cost') DEFAULT 'maximize_sales',
	`targetAcos` decimal(5,2),
	`targetRoas` decimal(10,2),
	`dailySpendLimit` decimal(10,2),
	`dailyCostTarget` decimal(10,2),
	`currentAcos` decimal(5,2),
	`currentRoas` decimal(10,2),
	`currentDailySpend` decimal(10,2),
	`currentDailySales` decimal(10,2),
	`conversionsPerDay` decimal(10,2),
	`status` enum('active','paused','archived') DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `performance_groups_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `product_targets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`adGroupId` int NOT NULL,
	`targetId` varchar(64),
	`targetType` enum('asin','category') NOT NULL,
	`targetValue` varchar(64) NOT NULL,
	`targetExpression` text,
	`bid` decimal(10,2) NOT NULL,
	`suggestedBid` decimal(10,2),
	`impressions` int DEFAULT 0,
	`clicks` int DEFAULT 0,
	`spend` decimal(10,2) DEFAULT '0.00',
	`sales` decimal(10,2) DEFAULT '0.00',
	`orders` int DEFAULT 0,
	`targetAcos` decimal(5,2),
	`targetOptimalBid` decimal(10,2),
	`targetStatus` enum('enabled','paused','archived') DEFAULT 'enabled',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `product_targets_id` PRIMARY KEY(`id`)
);
