CREATE TABLE `attribution_correction_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accountId` int NOT NULL,
	`biddingLogId` int NOT NULL,
	`campaignId` int NOT NULL,
	`correctionTargetType` enum('keyword','product_target') NOT NULL,
	`targetId` int NOT NULL,
	`targetName` varchar(500),
	`originalAdjustmentDate` timestamp NOT NULL,
	`originalBid` decimal(10,2) NOT NULL,
	`adjustedBid` decimal(10,2) NOT NULL,
	`adjustmentReason` varchar(255),
	`metricsAtAdjustment` text,
	`metricsAfterAttribution` text,
	`wasIncorrect` boolean DEFAULT false,
	`correctionType` enum('over_decreased','over_increased','correct'),
	`suggestedBid` decimal(10,2),
	`confidenceScore` decimal(3,2),
	`correctionStatus` enum('pending_review','approved','applied','dismissed') DEFAULT 'pending_review',
	`appliedAt` timestamp,
	`appliedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `attribution_correction_records_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `batch_operation_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`batchId` int NOT NULL,
	`entityType` enum('keyword','product_target','campaign','ad_group') NOT NULL,
	`entityId` int NOT NULL,
	`entityName` varchar(500),
	`negativeKeyword` varchar(500),
	`negativeMatchType` enum('negative_phrase','negative_exact'),
	`negativeLevel` enum('ad_group','campaign') DEFAULT 'ad_group',
	`currentBid` decimal(10,2),
	`newBid` decimal(10,2),
	`bidChangePercent` decimal(5,2),
	`bidChangeReason` varchar(255),
	`itemStatus` enum('pending','success','failed','skipped','rolled_back') DEFAULT 'pending',
	`errorMessage` text,
	`previousValue` text,
	`itemExecutedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `batch_operation_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `batch_operations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accountId` int,
	`operationType` enum('negative_keyword','bid_adjustment','keyword_migration','campaign_status') NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`batchStatus` enum('pending','approved','executing','completed','failed','cancelled','rolled_back') DEFAULT 'pending',
	`totalItems` int DEFAULT 0,
	`processedItems` int DEFAULT 0,
	`successItems` int DEFAULT 0,
	`failedItems` int DEFAULT 0,
	`requiresApproval` boolean DEFAULT true,
	`approvedBy` int,
	`approvedAt` timestamp,
	`executedBy` int,
	`executedAt` timestamp,
	`completedAt` timestamp,
	`canRollback` boolean DEFAULT true,
	`rolledBackAt` timestamp,
	`rolledBackBy` int,
	`sourceType` varchar(64),
	`sourceTaskId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `batch_operations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `correction_review_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accountId` int NOT NULL,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`totalAdjustmentsReviewed` int DEFAULT 0,
	`incorrectAdjustments` int DEFAULT 0,
	`overDecreasedCount` int DEFAULT 0,
	`overIncreasedCount` int DEFAULT 0,
	`correctCount` int DEFAULT 0,
	`estimatedLostRevenue` decimal(10,2),
	`estimatedWastedSpend` decimal(10,2),
	`potentialRecovery` decimal(10,2),
	`sessionStatus` enum('analyzing','ready_for_review','reviewed','corrections_applied') DEFAULT 'analyzing',
	`reviewedAt` timestamp,
	`reviewedBy` int,
	`correctionBatchId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `correction_review_sessions_id` PRIMARY KEY(`id`)
);
