CREATE TABLE `audit_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`userEmail` varchar(255),
	`userName` varchar(255),
	`actionType` enum('account_create','account_update','account_delete','account_connect','account_disconnect','campaign_create','campaign_update','campaign_delete','campaign_pause','campaign_enable','bid_adjust_single','bid_adjust_batch','bid_rollback','negative_add_single','negative_add_batch','negative_remove','performance_group_create','performance_group_update','performance_group_delete','automation_enable','automation_disable','automation_config_update','scheduler_task_create','scheduler_task_update','scheduler_task_delete','scheduler_task_run','team_member_invite','team_member_update','team_member_remove','team_permission_update','data_import','data_export','settings_update','notification_config_update','other') NOT NULL,
	`targetType` enum('account','campaign','ad_group','keyword','product_target','performance_group','negative_keyword','bid','automation','scheduler','team_member','permission','settings','data','other'),
	`targetId` varchar(255),
	`targetName` varchar(500),
	`description` text,
	`previousValue` json,
	`newValue` json,
	`metadata` json,
	`accountId` int,
	`accountName` varchar(255),
	`ipAddress` varchar(45),
	`userAgent` text,
	`requestId` varchar(64),
	`status` enum('success','failed','partial') DEFAULT 'success',
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `audit_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `collaboration_notification_rules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`triggerActions` json,
	`triggerAccountIds` json,
	`notifyChannels` json,
	`notifyRecipients` json,
	`notificationTemplate` text,
	`includeDetails` boolean DEFAULT true,
	`isActive` boolean DEFAULT true,
	`priority` enum('low','medium','high','critical') DEFAULT 'medium',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `collaboration_notification_rules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `collaboration_notifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ruleId` int,
	`auditLogId` int,
	`title` varchar(500) NOT NULL,
	`content` text NOT NULL,
	`actionType` varchar(100),
	`actionUserId` int,
	`actionUserName` varchar(255),
	`targetType` varchar(100),
	`targetId` varchar(255),
	`targetName` varchar(500),
	`accountId` int,
	`accountName` varchar(255),
	`channel` enum('app','email') NOT NULL,
	`recipientUserId` int NOT NULL,
	`recipientEmail` varchar(255),
	`status` enum('pending','sent','read','failed') DEFAULT 'pending',
	`readAt` timestamp,
	`sentAt` timestamp,
	`errorMessage` text,
	`priority` enum('low','medium','high','critical') DEFAULT 'medium',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `collaboration_notifications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_notification_preferences` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`enableAppNotifications` boolean DEFAULT true,
	`enableEmailNotifications` boolean DEFAULT true,
	`bidAdjustNotify` boolean DEFAULT true,
	`negativeKeywordNotify` boolean DEFAULT true,
	`campaignChangeNotify` boolean DEFAULT true,
	`automationNotify` boolean DEFAULT true,
	`teamChangeNotify` boolean DEFAULT true,
	`dataImportExportNotify` boolean DEFAULT false,
	`notifyOnLow` boolean DEFAULT false,
	`notifyOnMedium` boolean DEFAULT true,
	`notifyOnHigh` boolean DEFAULT true,
	`notifyOnCritical` boolean DEFAULT true,
	`quietHoursEnabled` boolean DEFAULT false,
	`quietHoursStart` varchar(5),
	`quietHoursEnd` varchar(5),
	`timezone` varchar(64) DEFAULT 'Asia/Shanghai',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_notification_preferences_id` PRIMARY KEY(`id`)
);
