CREATE TABLE `budget_allocation_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`allocationId` int NOT NULL,
	`campaignId` int NOT NULL,
	`currentBudget` decimal(10,2) NOT NULL,
	`recommendedBudget` decimal(10,2) NOT NULL,
	`budgetChange` decimal(10,2) NOT NULL,
	`changePercent` decimal(10,2) NOT NULL,
	`historicalSpend` decimal(15,2),
	`historicalSales` decimal(15,2),
	`historicalRoas` decimal(10,2),
	`historicalAcos` decimal(10,2),
	`historicalCtr` decimal(10,4),
	`historicalCvr` decimal(10,4),
	`predictedSpend` decimal(15,2),
	`predictedSales` decimal(15,2),
	`predictedRoas` decimal(10,2),
	`predictedAcos` decimal(10,2),
	`allocationReason` enum('high_roas','low_acos','high_conversion','growth_potential','new_product','seasonal_boost','low_roas','high_acos','low_conversion','budget_limit','maintain','rebalance'),
	`reasonDetail` text,
	`priorityScore` decimal(5,2),
	`status` enum('pending','applied','skipped') DEFAULT 'pending',
	`appliedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `budget_allocation_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `budget_allocations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accountId` int,
	`goalId` int,
	`allocationName` varchar(255) NOT NULL,
	`description` text,
	`totalBudget` decimal(15,2) NOT NULL,
	`allocatedBudget` decimal(15,2) NOT NULL,
	`predictedSales` decimal(15,2),
	`predictedRoas` decimal(10,2),
	`predictedAcos` decimal(10,2),
	`confidenceScore` decimal(5,2),
	`status` enum('draft','pending','approved','applied','rejected') DEFAULT 'draft',
	`appliedAt` timestamp,
	`appliedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `budget_allocations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `budget_goals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accountId` int,
	`goalType` enum('sales_target','roas_target','acos_target','profit_target','market_share') NOT NULL,
	`targetValue` decimal(15,2) NOT NULL,
	`periodType` enum('daily','weekly','monthly','quarterly') DEFAULT 'monthly',
	`startDate` timestamp,
	`endDate` timestamp,
	`totalBudget` decimal(15,2),
	`minCampaignBudget` decimal(10,2) DEFAULT '10.00',
	`maxCampaignBudget` decimal(10,2),
	`prioritizeHighRoas` boolean DEFAULT true,
	`prioritizeNewProducts` boolean DEFAULT false,
	`status` enum('active','paused','completed','expired') DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `budget_goals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `budget_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accountId` int,
	`campaignId` int NOT NULL,
	`allocationId` int,
	`previousBudget` decimal(10,2) NOT NULL,
	`newBudget` decimal(10,2) NOT NULL,
	`changeAmount` decimal(10,2) NOT NULL,
	`changePercent` decimal(10,2) NOT NULL,
	`source` enum('manual','auto_allocation','scheduled','rule_based','api_sync') NOT NULL,
	`reason` text,
	`snapshotRoas` decimal(10,2),
	`snapshotAcos` decimal(10,2),
	`snapshotSpend` decimal(15,2),
	`snapshotSales` decimal(15,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `budget_history_id` PRIMARY KEY(`id`)
);
