CREATE TABLE `api_call_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`accountId` int NOT NULL,
	`apiType` varchar(50) NOT NULL,
	`endpoint` varchar(255) NOT NULL,
	`method` varchar(10) NOT NULL,
	`statusCode` int,
	`responseTime` int,
	`isError` boolean DEFAULT false,
	`errorCode` varchar(50),
	`errorMessage` text,
	`retryCount` int DEFAULT 0,
	`isRetry` boolean DEFAULT false,
	`originalRequestId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `api_call_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `api_rate_limits` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`apiType` enum('campaigns','ad_groups','keywords','reports','bidding','bulk_operations') NOT NULL,
	`maxRequestsPerSecond` int DEFAULT 10,
	`maxRequestsPerMinute` int DEFAULT 100,
	`maxRequestsPerDay` int DEFAULT 10000,
	`currentSecondCount` int DEFAULT 0,
	`currentMinuteCount` int DEFAULT 0,
	`currentDayCount` int DEFAULT 0,
	`secondResetAt` timestamp,
	`minuteResetAt` timestamp,
	`dayResetAt` timestamp,
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `api_rate_limits_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `api_request_queue` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`accountId` int NOT NULL,
	`apiType` varchar(50) NOT NULL,
	`endpoint` varchar(255) NOT NULL,
	`method` varchar(10) NOT NULL,
	`requestBody` json,
	`priority` enum('low','normal','high','critical') DEFAULT 'normal',
	`status` enum('pending','processing','completed','failed','cancelled') DEFAULT 'pending',
	`maxRetries` int DEFAULT 3,
	`retryCount` int DEFAULT 0,
	`retryAfter` timestamp,
	`responseData` json,
	`errorMessage` text,
	`scheduledAt` timestamp,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `api_request_queue_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `budget_alert_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accountId` int,
	`overspendingThreshold` decimal(5,2) DEFAULT '120',
	`underspendingThreshold` decimal(5,2) DEFAULT '50',
	`nearDepletionThreshold` decimal(5,2) DEFAULT '90',
	`checkFrequency` enum('hourly','every_4_hours','daily') DEFAULT 'every_4_hours',
	`enableNotifications` boolean DEFAULT true,
	`notifyOnOverspending` boolean DEFAULT true,
	`notifyOnUnderspending` boolean DEFAULT true,
	`notifyOnDepletion` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `budget_alert_settings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `budget_allocation_tracking` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accountId` int,
	`allocationId` int NOT NULL,
	`trackingPeriod` enum('7_days','14_days','30_days') DEFAULT '7_days',
	`startDate` timestamp NOT NULL,
	`endDate` timestamp,
	`baselineStartDate` timestamp NOT NULL,
	`baselineEndDate` timestamp NOT NULL,
	`baselineSpend` decimal(15,2),
	`baselineSales` decimal(15,2),
	`baselineRoas` decimal(10,2),
	`baselineAcos` decimal(10,2),
	`baselineConversions` int,
	`baselineCtr` decimal(10,4),
	`baselineCpc` decimal(10,2),
	`currentSpend` decimal(15,2),
	`currentSales` decimal(15,2),
	`currentRoas` decimal(10,2),
	`currentAcos` decimal(10,2),
	`currentConversions` int,
	`currentCtr` decimal(10,4),
	`currentCpc` decimal(10,2),
	`roasChange` decimal(10,2),
	`acosChange` decimal(10,2),
	`salesChange` decimal(15,2),
	`spendChange` decimal(15,2),
	`effectRating` enum('excellent','good','neutral','poor','very_poor'),
	`effectSummary` text,
	`status` enum('tracking','completed','cancelled') DEFAULT 'tracking',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `budget_allocation_tracking_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `budget_consumption_alerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accountId` int,
	`campaignId` int NOT NULL,
	`alertType` enum('overspending','underspending','budget_depleted','near_depletion') NOT NULL,
	`severity` enum('low','medium','high','critical') DEFAULT 'medium',
	`dailyBudget` decimal(10,2) NOT NULL,
	`currentSpend` decimal(10,2) NOT NULL,
	`expectedSpend` decimal(10,2),
	`spendRate` decimal(10,4),
	`projectedDailySpend` decimal(10,2),
	`deviationPercent` decimal(10,2),
	`recommendation` text,
	`status` enum('active','acknowledged','resolved') DEFAULT 'active',
	`acknowledgedAt` timestamp,
	`resolvedAt` timestamp,
	`notificationSent` boolean DEFAULT false,
	`notificationSentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `budget_consumption_alerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `data_sync_schedules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accountId` int NOT NULL,
	`syncType` enum('campaigns','ad_groups','keywords','product_targets','search_terms','performance_daily','performance_hourly','full_sync') NOT NULL,
	`frequency` enum('hourly','every_4_hours','every_6_hours','every_12_hours','daily','weekly') DEFAULT 'daily',
	`preferredTime` varchar(5),
	`preferredDayOfWeek` int,
	`isEnabled` boolean DEFAULT true,
	`lastRunAt` timestamp,
	`nextRunAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `data_sync_schedules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `data_sync_tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accountId` int NOT NULL,
	`syncType` enum('campaigns','ad_groups','keywords','product_targets','search_terms','performance_daily','performance_hourly','full_sync') NOT NULL,
	`startDate` timestamp,
	`endDate` timestamp,
	`status` enum('pending','running','completed','failed','cancelled') DEFAULT 'pending',
	`totalItems` int,
	`processedItems` int DEFAULT 0,
	`failedItems` int DEFAULT 0,
	`resultSummary` json,
	`errorMessage` text,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `data_sync_tasks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `promotional_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventName` varchar(100) NOT NULL,
	`eventType` enum('prime_day','black_friday','cyber_monday','christmas','new_year','valentines','mothers_day','fathers_day','back_to_school','halloween','custom') NOT NULL,
	`marketplace` varchar(20),
	`startDate` timestamp NOT NULL,
	`endDate` timestamp NOT NULL,
	`warmupStartDate` timestamp,
	`warmupEndDate` timestamp,
	`recommendedBudgetMultiplier` decimal(5,2) DEFAULT '1.5',
	`warmupBudgetMultiplier` decimal(5,2) DEFAULT '1.2',
	`description` text,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `promotional_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `seasonal_budget_recommendations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accountId` int,
	`campaignId` int,
	`eventId` int,
	`recommendationType` enum('event_increase','event_warmup','seasonal_increase','seasonal_decrease','trend_based') NOT NULL,
	`currentBudget` decimal(10,2) NOT NULL,
	`recommendedBudget` decimal(10,2) NOT NULL,
	`budgetMultiplier` decimal(5,2),
	`effectiveStartDate` timestamp NOT NULL,
	`effectiveEndDate` timestamp NOT NULL,
	`expectedSalesIncrease` decimal(10,2),
	`expectedRoasChange` decimal(10,2),
	`reasoning` text,
	`confidenceScore` decimal(5,2),
	`status` enum('pending','applied','skipped','expired') DEFAULT 'pending',
	`appliedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `seasonal_budget_recommendations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `seasonal_trends` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accountId` int,
	`year` int NOT NULL,
	`month` int NOT NULL,
	`weekOfYear` int,
	`avgDailySpend` decimal(15,2),
	`avgDailySales` decimal(15,2),
	`avgRoas` decimal(10,2),
	`avgAcos` decimal(10,2),
	`avgConversions` decimal(10,2),
	`yoySpendChange` decimal(10,2),
	`yoySalesChange` decimal(10,2),
	`seasonalIndex` decimal(10,4) DEFAULT '1.0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `seasonal_trends_id` PRIMARY KEY(`id`)
);
