CREATE TABLE `ai_optimization_actions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`executionId` int NOT NULL,
	`aiActionType` enum('bid_increase','bid_decrease','bid_set','enable_target','pause_target','add_negative_phrase','add_negative_exact') NOT NULL,
	`aiTargetType` enum('keyword','product_target','search_term') NOT NULL,
	`aiTargetId` int,
	`aiTargetText` varchar(500),
	`previousValue` varchar(100),
	`newValue` varchar(100),
	`changeReason` text,
	`aiActionStatus` enum('pending','success','failed') DEFAULT 'pending',
	`aiActionError` text,
	`aiActionExecutedAt` timestamp,
	`aiActionCreatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ai_optimization_actions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_optimization_executions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accountId` int NOT NULL,
	`campaignId` int NOT NULL,
	`executionName` varchar(255),
	`aiExecType` enum('bid_adjustment','status_change','negative_keyword','mixed') NOT NULL,
	`aiExecStatus` enum('pending','executing','completed','failed','partially_completed') DEFAULT 'pending',
	`totalActions` int DEFAULT 0,
	`successfulActions` int DEFAULT 0,
	`failedActions` int DEFAULT 0,
	`aiAnalysisSummary` text,
	`baselineSpend` decimal(12,2),
	`baselineSales` decimal(12,2),
	`baselineAcos` decimal(5,2),
	`baselineRoas` decimal(10,2),
	`baselineClicks` int,
	`baselineImpressions` int,
	`baselineOrders` int,
	`executedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ai_optimization_executions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_optimization_predictions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`executionId` int NOT NULL,
	`predictionPeriod` enum('7_days','14_days','30_days') NOT NULL,
	`predictedSpend` decimal(12,2),
	`predictedSales` decimal(12,2),
	`predictedAcos` decimal(5,2),
	`predictedRoas` decimal(10,2),
	`predictedClicks` int,
	`predictedImpressions` int,
	`predictedOrders` int,
	`spendChangePercent` decimal(5,2),
	`salesChangePercent` decimal(5,2),
	`acosChangePercent` decimal(5,2),
	`roasChangePercent` decimal(5,2),
	`confidenceLevel` decimal(3,2),
	`predictionRationale` text,
	`predictionCreatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ai_optimization_predictions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_optimization_reviews` (
	`id` int AUTO_INCREMENT NOT NULL,
	`executionId` int NOT NULL,
	`predictionId` int NOT NULL,
	`reviewPeriod` enum('7_days','14_days','30_days') NOT NULL,
	`actualSpend` decimal(12,2),
	`actualSales` decimal(12,2),
	`actualAcos` decimal(5,2),
	`actualRoas` decimal(10,2),
	`actualClicks` int,
	`actualImpressions` int,
	`actualOrders` int,
	`actualSpendChange` decimal(5,2),
	`actualSalesChange` decimal(5,2),
	`actualAcosChange` decimal(5,2),
	`actualRoasChange` decimal(5,2),
	`spendAccuracy` decimal(5,2),
	`salesAccuracy` decimal(5,2),
	`acosAccuracy` decimal(5,2),
	`roasAccuracy` decimal(5,2),
	`overallAccuracy` decimal(5,2),
	`reviewStatus` enum('pending','completed','skipped') DEFAULT 'pending',
	`reviewSummary` text,
	`lessonsLearned` text,
	`scheduledAt` timestamp NOT NULL,
	`reviewedAt` timestamp,
	`reviewCreatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ai_optimization_reviews_id` PRIMARY KEY(`id`)
);
