CREATE TABLE `placement_adjustment_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`campaignId` varchar(50) NOT NULL,
	`accountId` int NOT NULL,
	`placement` enum('top_of_search','product_page') NOT NULL,
	`previousAdjustment` int NOT NULL,
	`newAdjustment` int NOT NULL,
	`reason` text,
	`snapshotImpressions` int,
	`snapshotClicks` int,
	`snapshotSpend` decimal(12,2),
	`snapshotSales` decimal(12,2),
	`snapshotAcos` decimal(8,4),
	`snapshotRoas` decimal(10,2),
	`efficiencyScore` decimal(5,2),
	`expectedAcosChange` decimal(8,4),
	`expectedRoasChange` decimal(10,2),
	`actualAcosChange` decimal(8,4),
	`actualRoasChange` decimal(10,2),
	`reviewedAt` timestamp,
	`status` enum('pending','executed','failed','reviewed') DEFAULT 'pending',
	`executedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `placement_adjustment_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `placement_performance` (
	`id` int AUTO_INCREMENT NOT NULL,
	`campaignId` varchar(50) NOT NULL,
	`accountId` int NOT NULL,
	`placement` enum('top_of_search','product_page','rest_of_search') NOT NULL,
	`date` date NOT NULL,
	`timeSlot` int,
	`impressions` int DEFAULT 0,
	`clicks` int DEFAULT 0,
	`spend` decimal(12,2) DEFAULT '0',
	`sales` decimal(12,2) DEFAULT '0',
	`orders` int DEFAULT 0,
	`ctr` decimal(8,6),
	`cpc` decimal(10,2),
	`cvr` decimal(8,6),
	`acos` decimal(8,4),
	`roas` decimal(10,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `placement_performance_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `placement_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`campaignId` varchar(50) NOT NULL,
	`accountId` int NOT NULL,
	`topOfSearchAdjustment` int DEFAULT 0,
	`productPageAdjustment` int DEFAULT 0,
	`autoOptimize` boolean DEFAULT true,
	`optimizationGoal` enum('roas','acos','sales','profit') DEFAULT 'roas',
	`targetAcos` decimal(5,2) DEFAULT '30.00',
	`targetRoas` decimal(5,2) DEFAULT '3.00',
	`minAdjustment` int DEFAULT 0,
	`maxAdjustment` int DEFAULT 200,
	`adjustmentStep` int DEFAULT 10,
	`adjustmentFrequency` enum('every_2_hours','every_4_hours','every_6_hours','daily') DEFAULT 'every_2_hours',
	`minClicksForDecision` int DEFAULT 50,
	`minSpendForDecision` decimal(10,2) DEFAULT '20.00',
	`lastAdjustedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `placement_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `placement_settings_campaignId_unique` UNIQUE(`campaignId`)
);
--> statement-breakpoint
CREATE TABLE `time_slot_bid_adjustments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`campaignId` varchar(50) NOT NULL,
	`accountId` int NOT NULL,
	`timeSlot` int NOT NULL,
	`bidAdjustmentPercent` int DEFAULT 0,
	`enabled` boolean DEFAULT true,
	`suggestedAdjustment` int,
	`efficiencyScore` decimal(5,2),
	`avgImpressions` int,
	`avgClicks` int,
	`avgSpend` decimal(10,2),
	`avgSales` decimal(10,2),
	`avgAcos` decimal(8,4),
	`avgRoas` decimal(10,2),
	`lastCalculatedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `time_slot_bid_adjustments_id` PRIMARY KEY(`id`)
);
