CREATE TABLE `bid_object_profit_estimates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`campaignId` varchar(50) NOT NULL,
	`bidObjectType` enum('keyword','asin') NOT NULL,
	`bidObjectId` varchar(100) NOT NULL,
	`baseBid` decimal(10,4),
	`recommendedBaseBid` decimal(10,4),
	`topOfSearchAdjustment` int DEFAULT 0,
	`productPageAdjustment` int DEFAULT 0,
	`recommendedTopAdjustment` int,
	`recommendedProductAdjustment` int,
	`effectiveBidTop` decimal(10,4),
	`effectiveBidProduct` decimal(10,4),
	`effectiveBidRest` decimal(10,4),
	`estimatedProfitTop` decimal(12,2),
	`estimatedProfitProduct` decimal(12,2),
	`estimatedProfitRest` decimal(12,2),
	`totalEstimatedProfit` decimal(12,2),
	`estimatedClicksTop` int,
	`estimatedClicksProduct` int,
	`estimatedClicksRest` int,
	`estimatedSpendTop` decimal(12,2),
	`estimatedSpendProduct` decimal(12,2),
	`estimatedSpendRest` decimal(12,2),
	`totalEstimatedSpend` decimal(12,2),
	`estimatedRevenueTop` decimal(12,2),
	`estimatedRevenueProduct` decimal(12,2),
	`estimatedRevenueRest` decimal(12,2),
	`totalEstimatedRevenue` decimal(12,2),
	`estimatedROAS` decimal(10,4),
	`estimatedACoS` decimal(8,4),
	`profitImprovementPotential` decimal(12,2),
	`profitImprovementPercent` decimal(8,4),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bid_object_profit_estimates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `bid_performance_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`campaignId` varchar(50) NOT NULL,
	`bidObjectType` enum('keyword','asin') NOT NULL,
	`bidObjectId` varchar(100) NOT NULL,
	`bid` decimal(10,4) NOT NULL,
	`effectiveCPC` decimal(10,4),
	`date` date NOT NULL,
	`timeSlot` int,
	`impressions` int DEFAULT 0,
	`clicks` int DEFAULT 0,
	`spend` decimal(12,2) DEFAULT '0',
	`sales` decimal(12,2) DEFAULT '0',
	`orders` int DEFAULT 0,
	`ctr` decimal(8,6),
	`cvr` decimal(8,6),
	`acos` decimal(8,4),
	`roas` decimal(10,4),
	`revenue` decimal(12,2),
	`profit` decimal(12,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `bid_performance_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `decision_tree_models` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`modelType` enum('cr_prediction','cv_prediction') NOT NULL,
	`treeStructure` json,
	`totalSamples` int,
	`treeDepth` int,
	`leafCount` int,
	`avgLeafSamples` decimal(10,2),
	`trainingR2` decimal(5,4),
	`validationR2` decimal(5,4),
	`meanAbsoluteError` decimal(10,6),
	`featureImportance` json,
	`version` int DEFAULT 1,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `decision_tree_models_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `keyword_predictions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`keywordId` int NOT NULL,
	`predictedCR` decimal(8,6),
	`predictedCV` decimal(12,2),
	`crLow` decimal(8,6),
	`crHigh` decimal(8,6),
	`cvLow` decimal(12,2),
	`cvHigh` decimal(12,2),
	`predictionSource` enum('historical','decision_tree','bayesian_update') DEFAULT 'decision_tree',
	`confidence` decimal(5,4),
	`sampleCount` int,
	`matchType` enum('broad','phrase','exact'),
	`wordCount` int,
	`keywordType` enum('brand','competitor','generic','product'),
	`actualCR` decimal(8,6),
	`actualCV` decimal(12,2),
	`predictionError` decimal(8,6),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `keyword_predictions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `market_curve_models` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`campaignId` varchar(50) NOT NULL,
	`bidObjectType` enum('keyword','asin','audience') NOT NULL,
	`bidObjectId` varchar(100) NOT NULL,
	`bidObjectText` varchar(500),
	`impressionCurveA` decimal(15,6),
	`impressionCurveB` decimal(15,6),
	`impressionCurveC` decimal(15,6),
	`impressionCurveR2` decimal(5,4),
	`baseCTR` decimal(8,6),
	`positionBonus` decimal(8,6),
	`topSearchCTRBonus` decimal(8,6),
	`cvr` decimal(8,6),
	`aov` decimal(12,2),
	`conversionDelayDays` int DEFAULT 7,
	`cvrSource` enum('historical','decision_tree','bayesian') DEFAULT 'historical',
	`optimalBid` decimal(10,4),
	`maxProfit` decimal(12,2),
	`profitMargin` decimal(5,4),
	`breakEvenCPC` decimal(10,4),
	`currentBid` decimal(10,4),
	`bidGap` decimal(10,4),
	`bidGapPercent` decimal(8,4),
	`dataPoints` int DEFAULT 0,
	`confidence` decimal(5,4),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `market_curve_models_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `optimization_recommendations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountId` int NOT NULL,
	`campaignId` varchar(50),
	`bidObjectType` enum('keyword','asin','campaign','placement'),
	`bidObjectId` varchar(100),
	`recommendationType` enum('bid_adjustment','placement_adjustment','budget_reallocation','keyword_optimization','data_collection') NOT NULL,
	`priority` enum('critical','high','medium','low') DEFAULT 'medium',
	`title` varchar(255),
	`description` text,
	`expectedImpact` text,
	`currentValue` json,
	`recommendedValue` json,
	`expectedProfitChange` decimal(12,2),
	`expectedProfitChangePercent` decimal(8,4),
	`expectedAcosChange` decimal(8,4),
	`expectedRoasChange` decimal(10,4),
	`status` enum('pending','applied','rejected','expired') DEFAULT 'pending',
	`appliedAt` timestamp,
	`appliedBy` int,
	`actualProfitChange` decimal(12,2),
	`actualAcosChange` decimal(8,4),
	`actualRoasChange` decimal(10,4),
	`reviewedAt` timestamp,
	`expiresAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `optimization_recommendations_id` PRIMARY KEY(`id`)
);
