branch-defaults:
  main:
    environment: amazon-ads-env-prod
environment-defaults:
  amazon-ads-env-prod:
    branch: null
    repository: null
global:
  application_name: amazon-ads-optimizer
  default_ec2_keyname: null
  default_platform: Node.js 20
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
