-- v446 Database Index Optimization Migration
-- Total: 84 indexes
-- Generated: 2026-03-18

CREATE INDEX IF NOT EXISTS `idx_dsj_accountId` ON `data_sync_jobs` (account_id);
CREATE INDEX IF NOT EXISTS `idx_dsj_status` ON `data_sync_jobs` (status);
CREATE INDEX IF NOT EXISTS `idx_dsj_userId` ON `data_sync_jobs` (user_id);
CREATE INDEX IF NOT EXISTS `idx_dsj_account_status` ON `data_sync_jobs` (account_id, status);
CREATE INDEX IF NOT EXISTS `idx_dsj_startedAt` ON `data_sync_jobs` (started_at);
CREATE INDEX IF NOT EXISTS `idx_dsl_jobId` ON `data_sync_logs` (job_id);
CREATE INDEX IF NOT EXISTS `idx_dsl_status` ON `data_sync_logs` (status);
CREATE INDEX IF NOT EXISTS `idx_hp_accountId` ON `hourly_performance` (account_id);
CREATE INDEX IF NOT EXISTS `idx_hp_campaignId` ON `hourly_performance` (campaign_id);
CREATE INDEX IF NOT EXISTS `idx_hp_date` ON `hourly_performance` (date);
CREATE INDEX IF NOT EXISTS `idx_hp_account_campaign` ON `hourly_performance` (account_id, campaign_id);
CREATE INDEX IF NOT EXISTS `idx_pp_accountId` ON `placement_performance` (account_id);
CREATE INDEX IF NOT EXISTS `idx_pp_campaignId` ON `placement_performance` (campaign_id);
CREATE INDEX IF NOT EXISTS `idx_pp_date` ON `placement_performance` (date);
CREATE INDEX IF NOT EXISTS `idx_pp_account_campaign` ON `placement_performance` (account_id, campaign_id);
CREATE INDEX IF NOT EXISTS `idx_bph_accountId` ON `bid_performance_history` (account_id);
CREATE INDEX IF NOT EXISTS `idx_bph_bidObjectId` ON `bid_performance_history` (bid_object_id);
CREATE INDEX IF NOT EXISTS `idx_bph_account_object` ON `bid_performance_history` (account_id, bid_object_type, bid_object_id);
CREATE INDEX IF NOT EXISTS `idx_bph_campaignId` ON `bid_performance_history` (campaign_id);
CREATE INDEX IF NOT EXISTS `idx_bph_createdAt` ON `bid_performance_history` (created_at);
CREATE INDEX IF NOT EXISTS `idx_bl_accountId` ON `bidding_logs` (account_id);
CREATE INDEX IF NOT EXISTS `idx_bl_campaignId` ON `bidding_logs` (campaign_id);
CREATE INDEX IF NOT EXISTS `idx_bl_targetId` ON `bidding_logs` (target_id);
CREATE INDEX IF NOT EXISTS `idx_bl_createdAt` ON `bidding_logs` (created_at);
CREATE INDEX IF NOT EXISTS `idx_bl_actionType` ON `bidding_logs` (action_type);
CREATE INDEX IF NOT EXISTS `idx_pg_accountId` ON `performance_groups` (account_id);
CREATE INDEX IF NOT EXISTS `idx_pg_userId` ON `performance_groups` (user_id);
CREATE INDEX IF NOT EXISTS `idx_pg_status` ON `performance_groups` (status);
CREATE INDEX IF NOT EXISTS `idx_pg_account_status` ON `performance_groups` (account_id, status);
CREATE INDEX IF NOT EXISTS `idx_bh_accountId` ON `budget_history` (account_id);
CREATE INDEX IF NOT EXISTS `idx_bh_userId` ON `budget_history` (user_id);
CREATE INDEX IF NOT EXISTS `idx_bh_campaignId` ON `budget_history` (campaign_id);
CREATE INDEX IF NOT EXISTS `idx_bh_createdAt` ON `budget_history` (created_at);
CREATE INDEX IF NOT EXISTS `idx_al_accountId` ON `audit_logs` (account_id);
CREATE INDEX IF NOT EXISTS `idx_al_userId` ON `audit_logs` (user_id);
CREATE INDEX IF NOT EXISTS `idx_al_actionType` ON `audit_logs` (action_type);
CREATE INDEX IF NOT EXISTS `idx_al_createdAt` ON `audit_logs` (created_at);
CREATE INDEX IF NOT EXISTS `idx_al_account_action` ON `audit_logs` (account_id, action_type);
CREATE INDEX IF NOT EXISTS `idx_acl_accountId` ON `api_call_logs` (account_id);
CREATE INDEX IF NOT EXISTS `idx_acl_userId` ON `api_call_logs` (user_id);
CREATE INDEX IF NOT EXISTS `idx_acl_apiType` ON `api_call_logs` (api_type);
CREATE INDEX IF NOT EXISTS `idx_acl_createdAt` ON `api_call_logs` (created_at);
CREATE INDEX IF NOT EXISTS `idx_acl_statusCode` ON `api_call_logs` (status_code);
CREATE INDEX IF NOT EXISTS `idx_aol_accountId` ON `api_operation_logs` (account_id);
CREATE INDEX IF NOT EXISTS `idx_aol_userId` ON `api_operation_logs` (user_id);
CREATE INDEX IF NOT EXISTS `idx_aol_operationType` ON `api_operation_logs` (operation_type);
CREATE INDEX IF NOT EXISTS `idx_aol_status` ON `api_operation_logs` (status);
CREATE INDEX IF NOT EXISTS `idx_aol_createdAt` ON `api_operation_logs` (created_at);
CREATE INDEX IF NOT EXISTS `idx_arq_accountId` ON `api_request_queue` (account_id);
CREATE INDEX IF NOT EXISTS `idx_arq_status` ON `api_request_queue` (status);
CREATE INDEX IF NOT EXISTS `idx_arq_priority_status` ON `api_request_queue` (priority, status);
CREATE INDEX IF NOT EXISTS `idx_arq_scheduledAt` ON `api_request_queue` (scheduled_at);
CREATE INDEX IF NOT EXISTS `idx_or_accountId` ON `optimization_recommendations` (account_id);
CREATE INDEX IF NOT EXISTS `idx_or_campaignId` ON `optimization_recommendations` (campaign_id);
CREATE INDEX IF NOT EXISTS `idx_or_status` ON `optimization_recommendations` (status);
CREATE INDEX IF NOT EXISTS `idx_or_priority` ON `optimization_recommendations` (priority);
CREATE INDEX IF NOT EXISTS `idx_or_account_status` ON `optimization_recommendations` (account_id, status);
CREATE INDEX IF NOT EXISTS `idx_nh_userId` ON `notification_history` (user_id);
CREATE INDEX IF NOT EXISTS `idx_nh_accountId` ON `notification_history` (account_id);
CREATE INDEX IF NOT EXISTS `idx_nh_status` ON `notification_history` (status);
CREATE INDEX IF NOT EXISTS `idx_nh_createdAt` ON `notification_history` (created_at);
CREATE INDEX IF NOT EXISTS `idx_tel_accountId` ON `task_execution_log` (account_id);
CREATE INDEX IF NOT EXISTS `idx_tel_userId` ON `task_execution_log` (user_id);
CREATE INDEX IF NOT EXISTS `idx_tel_taskType` ON `task_execution_log` (task_type);
CREATE INDEX IF NOT EXISTS `idx_tel_status` ON `task_execution_log` (status);
CREATE INDEX IF NOT EXISTS `idx_tel_createdAt` ON `task_execution_log` (created_at);
CREATE INDEX IF NOT EXISTS `idx_bo_userId` ON `batch_operations` (user_id);
CREATE INDEX IF NOT EXISTS `idx_bo_accountId` ON `batch_operations` (account_id);
CREATE INDEX IF NOT EXISTS `idx_bo_batchStatus` ON `batch_operations` (batch_status);
CREATE INDEX IF NOT EXISTS `idx_bo_createdAt` ON `batch_operations` (created_at);
CREATE INDEX IF NOT EXISTS `idx_boi_batchId` ON `batch_operation_items` (batch_id);
CREATE INDEX IF NOT EXISTS `idx_boi_itemStatus` ON `batch_operation_items` (item_status);
CREATE INDEX IF NOT EXISTS `idx_ds_accountId` ON `dayparting_strategies` (account_id);
CREATE INDEX IF NOT EXISTS `idx_ds_campaignId` ON `dayparting_strategies` (campaign_id);
CREATE INDEX IF NOT EXISTS `idx_ds_account_campaign` ON `dayparting_strategies` (account_id, campaign_id);
CREATE INDEX IF NOT EXISTS `idx_apr_accountId` ON `auto_pause_records` (account_id);
CREATE INDEX IF NOT EXISTS `idx_apr_userId` ON `auto_pause_records` (user_id);
CREATE INDEX IF NOT EXISTS `idx_apr_pausedAt` ON `auto_pause_records` (paused_at);
CREATE INDEX IF NOT EXISTS `idx_adGroups_adGroupId` ON `ad_groups` (ad_group_id);
CREATE INDEX IF NOT EXISTS `idx_keywords_keywordStatus` ON `keywords` (keyword_status);
CREATE INDEX IF NOT EXISTS `idx_negKw_internalAdGroupId` ON `negative_keywords` (internal_ad_group_id);
CREATE INDEX IF NOT EXISTS `idx_negKw_negativeLevel` ON `negative_keywords` (negative_level);
CREATE INDEX IF NOT EXISTS `idx_prodTargets_internalAdGroupId` ON `product_targets` (internal_ad_group_id);
CREATE INDEX IF NOT EXISTS `idx_prodTargets_targetStatus` ON `product_targets` (target_status);
